// Generates src/scene3d/catalog.generated.ts from the Kenney Furniture Kit glb
// files in public/kenney3d. Every number in the scene system's physical model
// (footprints, heights, surface tops) comes from THIS measurement of the real
// geometry — never from a filename, a sprite canvas or an eyeballed offset.
//
//   node scripts/kenney-catalog.mjs
import fs from 'node:fs'
import path from 'node:path'

const dir = path.resolve('public/kenney3d')
const out = path.resolve('src/scene3d/catalog.generated.ts')

function parseGlb(buf) {
  const jsonLen = buf.readUInt32LE(12)
  return JSON.parse(buf.subarray(20, 20 + jsonLen).toString('utf8'))
}
function mul(a, b) {
  const o = new Array(16).fill(0)
  for (let c = 0; c < 4; c++) for (let r = 0; r < 4; r++) for (let k = 0; k < 4; k++) o[c * 4 + r] += a[k * 4 + r] * b[c * 4 + k]
  return o
}
function nodeMatrix(n) {
  if (n.matrix) return n.matrix
  const t = n.translation ?? [0, 0, 0], q = n.rotation ?? [0, 0, 0, 1], s = n.scale ?? [1, 1, 1]
  const [x, y, z, w] = q
  return [
    (1 - 2 * (y * y + z * z)) * s[0], (2 * (x * y + z * w)) * s[0], (2 * (x * z - y * w)) * s[0], 0,
    (2 * (x * y - z * w)) * s[1], (1 - 2 * (x * x + z * z)) * s[1], (2 * (y * z + x * w)) * s[1], 0,
    (2 * (x * z + y * w)) * s[2], (2 * (y * z - x * w)) * s[2], (1 - 2 * (x * x + y * y)) * s[2], 0,
    t[0], t[1], t[2], 1,
  ]
}
const xf = (m, p) => [
  m[0] * p[0] + m[4] * p[1] + m[8] * p[2] + m[12],
  m[1] * p[0] + m[5] * p[1] + m[9] * p[2] + m[13],
  m[2] * p[0] + m[6] * p[1] + m[10] * p[2] + m[14],
]
function bbox(json) {
  const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity]
  const walk = (ni, parent) => {
    const n = json.nodes[ni]
    const m = mul(parent, nodeMatrix(n))
    if (n.mesh !== undefined) for (const prim of json.meshes[n.mesh].primitives) {
      const acc = json.accessors[prim.attributes.POSITION]
      for (const cx of [acc.min[0], acc.max[0]]) for (const cy of [acc.min[1], acc.max[1]]) for (const cz of [acc.min[2], acc.max[2]]) {
        const p = xf(m, [cx, cy, cz])
        for (let i = 0; i < 3; i++) { min[i] = Math.min(min[i], p[i]); max[i] = Math.max(max[i], p[i]) }
      }
    }
    for (const c of n.children ?? []) walk(c, m)
  }
  const I = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
  for (const s of json.scenes[json.scene ?? 0].nodes) walk(s, I)
  return { min, max }
}

const r3 = v => Math.round(v * 1000) / 1000
const rows = []
for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.glb')).sort()) {
  const { min, max } = bbox(parseGlb(fs.readFileSync(path.join(dir, f))))
  const name = f.replace('.glb', '')
  rows.push(`  ${name}: { size: [${r3(max[0] - min[0])}, ${r3(max[1] - min[1])}, ${r3(max[2] - min[2])}], min: [${min.map(r3).join(', ')}] },`)
}
const body = `// GENERATED by scripts/kenney-catalog.mjs — do not edit by hand.
// Axis-aligned bounding boxes of every Kenney Furniture Kit model, measured
// from the glTF geometry with node transforms applied. Units are Kenney units
// (one floorFull tile = 1 × 1). size = [width x, height y, depth z]; min = the
// model's own bbox minimum, so min[1] === 0 means the model is grounded at its
// origin.
export const MODEL_BOUNDS = {
${rows.join('\n')}
} as const

export type KenneyModel = keyof typeof MODEL_BOUNDS
`
fs.writeFileSync(out, body)
console.log(`wrote ${rows.length} models to ${path.relative(process.cwd(), out)}`)
