import type { SceneSpec } from '../schema'

// Moradia estreita com galeria de jantar e dois jardins em faixas.
export const oneLastWaltz: SceneSpec = {
  puzzleId: 'medium-5',
  floor: 0,
  entry: { wall: 'west', at: 4.4 },
  shell: { features: [{ wall: 'north', at: 3.0, kind: 'window' }] },
  floors: [
    { id: 'entry-gallery', cells: [0, 0, 1, 7], material: 'tile', kind: 'interior' },
    { id: 'dining-gallery', cells: [2, 0, 3, 7], material: 'wood', kind: 'interior' },
    { id: 'front-court', cells: [4, 0, 5, 7], material: 'stone', kind: 'exterior' },
    { id: 'garden-walk', cells: [6, 0, 7, 7], material: 'grass', kind: 'exterior' },
  ],
  walls: [
    { id: 'gallery-dining', from: [2, 0], to: [2, 8], height: 'half', openings: [{ at: 4.5, width: 1.15, kind: 'door' }] },
    { id: 'dining-front-court', from: [4, 0], to: [4, 8], height: 'half', openings: [{ at: 5.2, width: 1.2, kind: 'open' }] },
  ],
  furniture: [
    // Galeria de entrada: relógio de pé e vaso a norte, banco e bengaleiro junto à porta,
    // rádios em prateleiras baixas e um segundo relógio de pé a sul da entrada.
    { id: 'gallery-plant-north', model: 'pottedPlant', logic: 'plant@0,0', at: [0.3, 0.3] },
    { id: 'gallery-clock-north', model: 'speaker', logic: 'clock@0,1', against: { wall: 'north', at: 1.55 } },
    { id: 'gallery-bench', model: 'benchCushion', against: { wall: 'west', at: 2.6 }, facing: 'E' },
    { id: 'gallery-coat-rack', model: 'coatRackStanding', at: [0.3, 3.6] },
    { id: 'gallery-clock-mid-table', model: 'bookcaseOpenLow', against: { wall: 'gallery-dining', at: 3.3, side: 'W' }, facing: 'W' },
    { id: 'gallery-clock-mid', model: 'radio', logic: 'clock@3,1', on: { parent: 'gallery-clock-mid-table', surface: 'top' } },
    { id: 'gallery-clock-south-west', model: 'speaker', logic: 'clock@5,0', against: { wall: 'west', at: 5.4 }, facing: 'E' },
    { id: 'gallery-clock-south-east-table', model: 'bookcaseOpenLow', against: { wall: 'gallery-dining', at: 5.75, side: 'W' }, facing: 'W' },
    { id: 'gallery-clock-south-east', model: 'radio', logic: 'clock@5,1', on: { parent: 'gallery-clock-south-east-table', surface: 'top' } },
    { id: 'gallery-bookcase-south', model: 'bookcaseClosed', against: { wall: 'west', at: 6.6 }, facing: 'E' },
    { id: 'gallery-plant-south', model: 'pottedPlant', logic: 'plant@7,0', at: [0.35, 7.3] },
    // Sala de jantar: mesa sob a janela com quatro cadeiras; recanto de conversa com poltrona,
    // candeeiro e sofá; estantes no extremo sul.
    { id: 'dining-table', model: 'tableCloth', logic: 'table@0,2', at: [3.0, 0.7] },
    { id: 'dining-chair-west', model: 'chair', at: [2.22, 0.7], facing: 'E' },
    { id: 'dining-chair-east', model: 'chair', at: [3.78, 0.7], facing: 'W' },
    { id: 'dining-chair-south-a', model: 'chair', at: [2.72, 1.28], facing: 'N' },
    { id: 'dining-chair-south-b', model: 'chair', at: [3.3, 1.28], facing: 'N' },
    { id: 'dining-lamp', model: 'lampRoundFloor', logic: 'lamp@1,2', at: [2.22, 1.8] },
    { id: 'dining-chair', model: 'loungeChair', logic: 'chair@2,2', at: [2.42, 2.65], facing: 'E' },
    { id: 'dining-sofa', model: 'loungeSofa', against: { wall: 'dining-front-court', at: 2.75, side: 'W' }, facing: 'W' },
    { id: 'dining-bookcase-south', model: 'bookcaseClosedWide', against: { wall: 'gallery-dining', at: 6.8, side: 'E' }, facing: 'E' },
    { id: 'dining-shelf-south', model: 'bookcaseOpenLow', against: { wall: 'dining-front-court', at: 7.2, side: 'W' }, facing: 'W' },
    { id: 'dining-shelf-lamp', model: 'lampSquareTable', on: { parent: 'dining-shelf-south', surface: 'top' } },
    // Pátio da frente: canteiros de arbustos ao longo da faixa e caminho de lajes até ao jardim.
    { id: 'court-shrub-north-east', model: 'plant_bushDetailed', logic: 'shrub@1,5', at: [5.42, 1.4] },
    { id: 'court-plant-mid-west', model: 'flower_redA', logic: 'plant@2,5', at: [5.4, 2.45] },
    { id: 'court-shrub-south-west', model: 'plant_bushSmall', logic: 'shrub@4,5', at: [5.5, 4.4] },
    { id: 'court-shrub-south', model: 'plant_bushSmall', logic: 'shrub@6,5', at: [5.55, 6.5] },
    { id: 'court-shrub-far-south', model: 'plant_bushSmall', logic: 'shrub@7,5', at: [5.5, 7.5] },
    { id: 'court-flower-a', model: 'flower_yellowA', at: [4.35, 2.2] },
    { id: 'court-rock', model: 'rock_smallA', at: [4.4, 7.3] },
    // Jardim: vedação baixa com passagem, canteiros, banco e flores.
    { id: 'garden-fence-a', model: 'fence_simpleLow', at: [6.05, 0.7], facing: 'E' },
    { id: 'garden-fence-b', model: 'fence_simpleLow', at: [6.05, 2.05], facing: 'E' },
    { id: 'garden-fence-c', model: 'fence_simpleLow', at: [6.05, 3.4], facing: 'E' },
    { id: 'garden-fence-d', model: 'fence_simpleLow', at: [6.05, 7.3], facing: 'E' },
    { id: 'court-plant-north-west', model: 'flower_yellowA', logic: 'plant@1,6', at: [6.5, 1.5] },
    { id: 'court-shrub-centre-west', model: 'plant_bushDetailed', logic: 'shrub@2,6', at: [6.6, 2.5] },
    { id: 'court-plant-south-east', model: 'flower_purpleA', logic: 'plant@1,7', at: [7.5, 1.5] },
    { id: 'garden-bench', model: 'bench', at: [7.6, 4.6], facing: 'W' },
    { id: 'garden-flower-b', model: 'flower_redA', at: [7.5, 3.4] },
    { id: 'garden-flower-c', model: 'flower_purpleA', at: [6.6, 6.4] },
    { id: 'garden-shrub', model: 'plant_bushDetailed', logic: 'shrub@7,7', at: [7.5, 7.5] },
  ],
  rugs: [
    { id: 'gallery-runner', model: 'rugRectangle', at: [1.0, 4.4], facing: 'E' },
    { id: 'dining-runner', model: 'rugRound', at: [3.0, 2.7] },
    { id: 'court-path-a', model: 'path_stone', at: [4.6, 5.2] },
    { id: 'court-path-b', model: 'path_stone', at: [5.5, 5.4] },
    { id: 'garden-path-a', model: 'path_stone', at: [6.5, 5.5] },
    { id: 'garden-path-b', model: 'path_stone', at: [7.3, 5.7] },
  ],
}
