import type { SceneSpec } from '../schema'

// Casa térrea em L com sala de jantar, corredor de distribuição e cozinha.
export const whispersUpstairs: SceneSpec = {
  puzzleId: 'medium-7',
  floor: 0,
  entry: { wall: 'west', at: 7.4 },
  shell: { features: [{ wall: 'north', at: 1.9, kind: 'window' }] },
  floors: [
    { id: 'dining-wing', cells: [0, 0, 2, 7], material: 'wood', kind: 'interior' },
    { id: 'front-yard', cells: [3, 0, 7, 2], material: 'grass', kind: 'exterior' },
    { id: 'cross-hallway', cells: [3, 3, 7, 4], material: 'tile', kind: 'interior' },
    { id: 'service-kitchen', cells: [3, 5, 7, 7], material: 'tile', kind: 'interior' },
  ],
  walls: [
    { id: 'dining-hallway', from: [3, 0], to: [3, 8], height: 'half', openings: [{ at: 4.0, width: 0.8, kind: 'door' }] },
    { id: 'yard-hallway', from: [3, 3], to: [8, 3], height: 'half', openings: [{ at: 7.4, width: 1.1, kind: 'open' }] },
    { id: 'hallway-kitchen', from: [3, 5], to: [8, 5], height: 'half', openings: [{ at: 7.4, width: 1.0, kind: 'open' }] },
  ],
  furniture: [
    // Sala de jantar: a norte uma sala de estar (sofá sobre o tapete, mesa baixa, televisão,
    // estante e candeeiro de pé); ao centro a mesa com a cadeira e o aparador; a sul o vestíbulo.
    { id: 'dining-rug', model: 'rugRectangle', logic: 'rug@1,0', at: [1.0, 2.0] },
    { id: 'living-sofa', model: 'loungeSofa', against: { wall: 'west', at: 2.0 }, facing: 'E' },
    { id: 'living-coffee-table', model: 'tableCoffee', at: [1.35, 2.0], facing: 'E' },
    { id: 'living-media', model: 'cabinetTelevision', against: { wall: 'dining-hallway', at: 2.0, side: 'W' }, facing: 'W' },
    { id: 'living-tv', model: 'televisionVintage', on: { parent: 'living-media' } },
    { id: 'living-bookcase', model: 'bookcaseClosedWide', against: { wall: 'north', at: 0.8 } },
    { id: 'dining-lamp-north', model: 'lampRoundFloor', logic: 'lamp@0,2', at: [2.6, 0.35] },
    { id: 'dining-table', model: 'tableCloth', logic: 'table@4,0', at: [1.5, 4.2], facing: 'E' },
    { id: 'dining-chair-east', model: 'chair', logic: 'chair@3,2', at: [2.05, 3.95], facing: 'W' },
    { id: 'dining-sideboard', model: 'cabinetTelevisionDoors', against: { wall: 'west', at: 4.2 }, facing: 'E' },
    { id: 'dining-lamp-south', model: 'lampRoundFloor', logic: 'lamp@5,2', at: [2.6, 5.3] },
    { id: 'dining-chair-south-west', model: 'chair', logic: 'chair@6,0', against: { wall: 'west', at: 6.45 }, facing: 'E' },
    { id: 'foyer-shelf', model: 'bookcaseOpenLow', against: { wall: 'dining-hallway', at: 7.0, side: 'W' }, facing: 'W' },
    { id: 'foyer-shelf-books', model: 'books', on: { parent: 'foyer-shelf', surface: 'top' } },
    // Pátio da frente: vedação, canteiros e caminho até ao corredor.
    { id: 'yard-shrub-north', model: 'plant_bushSmall', logic: 'shrub@0,5', at: [5.5, 0.5] },
    { id: 'yard-plant-west', model: 'flower_yellowA', logic: 'plant@0,4', at: [4.5, 0.5] },
    { id: 'yard-plant-east', model: 'flower_purpleA', logic: 'plant@0,6', at: [6.5, 0.5] },
    { id: 'yard-shrub-south-west', model: 'plant_bushDetailed', logic: 'shrub@2,4', at: [4.5, 2.4] },
    { id: 'yard-shrub-south-east', model: 'plant_bushSmall', logic: 'shrub@2,6', at: [6.45, 2.4] },
    { id: 'yard-plant-south', model: 'flower_redA', logic: 'plant@1,3', at: [3.55, 1.45] },
    { id: 'yard-fence-a', model: 'fence_simple', at: [4.0, 0.1], facing: 'S' },
    { id: 'yard-fence-b', model: 'fence_simple', at: [5.3, 0.1], facing: 'S' },
    { id: 'yard-fence-c', model: 'fence_simple', at: [6.6, 0.1], facing: 'S' },
    { id: 'yard-rock', model: 'rock_smallA', at: [5.4, 1.6] },
    // Corredor: dois relógios de pé a ladear a porta da sala de jantar, estante baixa e vaso.
    { id: 'hall-clock-north', model: 'speaker', logic: 'clock@3,3', against: { wall: 'yard-hallway', at: 3.75, side: 'S' } },
    { id: 'hall-clock-south', model: 'speaker', logic: 'clock@4,3', against: { wall: 'hallway-kitchen', at: 3.75, side: 'N' } },
    { id: 'hall-shelf', model: 'bookcaseOpenLow', against: { wall: 'yard-hallway', at: 5.3, side: 'S' } },
    { id: 'hall-shelf-books', model: 'books', on: { parent: 'hall-shelf', surface: 'top' } },
    { id: 'hall-plant', model: 'pottedPlant', logic: 'plant@4,5', at: [5.6, 4.65] },
    // Cozinha em U: bancada com lava-loiça na divisória norte, fogão na divisória oeste,
    // armários na parede sul entre os dois frigoríficos.
    { id: 'kitchen-cabinet-nw', model: 'kitchenCabinet', against: { wall: 'hallway-kitchen', at: 3.95, side: 'S' } },
    { id: 'kitchen-cabinet-n', model: 'kitchenCabinetDrawer', against: { wall: 'hallway-kitchen', at: 4.49, side: 'S' } },
    { id: 'kitchen-sink', model: 'kitchenSink', against: { wall: 'hallway-kitchen', at: 5.03, side: 'S' } },
    { id: 'kitchen-counter', model: 'kitchenCabinet', logic: 'counter@5,5', against: { wall: 'hallway-kitchen', at: 5.57, side: 'S' } },
    { id: 'kitchen-cabinet-ne', model: 'kitchenCabinetDrawer', against: { wall: 'hallway-kitchen', at: 6.11, side: 'S' } },
    { id: 'kitchen-coffee', model: 'kitchenCoffeeMachine', on: { parent: 'kitchen-cabinet-ne' } },
    { id: 'kitchen-stove', model: 'kitchenStoveElectric', logic: 'stove@6,3', against: { wall: 'dining-hallway', at: 6.4, side: 'E' }, facing: 'E' },
    { id: 'kitchen-cabinet-w', model: 'kitchenCabinet', against: { wall: 'dining-hallway', at: 6.94, side: 'E' }, facing: 'E' },
    { id: 'kitchen-fridge-west', model: 'kitchenFridgeSmall', logic: 'fridge@7,4', at: [4.5, 7.5], facing: 'E' },
    { id: 'kitchen-cabinet-s1', model: 'kitchenCabinet', against: { wall: 'south', at: 5.2 }, facing: 'N' },
    { id: 'kitchen-cabinet-s2', model: 'kitchenCabinetDrawer', against: { wall: 'south', at: 5.74 }, facing: 'N' },
    { id: 'kitchen-microwave', model: 'kitchenMicrowave', on: { parent: 'kitchen-cabinet-s2' } },
    { id: 'kitchen-fridge-east', model: 'kitchenFridgeSmall', logic: 'fridge@7,6', at: [6.6, 7.5], facing: 'S' },
  ],
  rugs: [
    { id: 'foyer-mat', model: 'rugDoormat', at: [0.35, 7.4], facing: 'E' },
    { id: 'hall-runner', model: 'rugRectangle', at: [5.6, 4.0] },
    { id: 'yard-path-a', model: 'path_stone', at: [7.3, 2.4] },
    { id: 'yard-path-b', model: 'path_stone', at: [7.3, 1.4] },
  ],
}
